[package]
name = "A100_veri-tipleri-ve-sentaks_alistirma_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
